language: csharp
# dist: focal
os:
    - linux
arch:
    - amd64
solution: src/digitales-wachbuch.sln
mono: none
dotnet: 6.0
script :
    - dotnet restore src
    - dotnet build src
before_deploy: "cd src"
deploy:
    provider: azure_web_apps
    edge: true
    skip_cleanup: true
    verbose: true
    on:
      branch: master
