query {
    activeSentry {
        id,
        start,
        end,
        registration,
        organisation {
            name
        },
        supervisors {
            start,
            end,
            guard {
                firstName
                lastName
            }
        },
        guards {
            start,
            end,
            guard {
                firstName,
                lastName
            }
        }
    }
}